exports.appName="suite"
exports.localization = {};
exports.localization.appName ={
  "en_US": "Calculator Suite",
  "ar": "Calculator Suite",
  "bg": "Calculator Suite",
  "bs": "Komplet kalkulatora",
  "ca": "Paquet d'aplicacions",
  "cs": "Calculator Suite",
  "da": "Matematikværktøjssuite",
  "de": "Rechner Suite",
  "el": "Calculator Suite",
  "es": "Suite Calculadora",
  "fa": "Calculator Suite",
  "fi": "Calculator Suite",
  "fr": "Calculatrice Suite",
  "hr": "Komplet kalkulatora",
  "hu": "Calculator Suite",
  "it": "Suite Calcolatrici",
  "ja": "GeoGebra????",
  "kk": "Calculator Suite",
  "ko": "??? ???",
  "lt": "Calculator Suite",
  "mn": "?????? ??????????",
  "nl": "Rekenmachine suite",
  "no": "Calculator Suite",
  "no_NO": "Calculator Suite",
  "no_NO_NY": "Calculator Suite",
  "pl": "Calculator Suite",
  "pt": "Calculadora",
  "ro": "Calculator Suite",
  "ru": "Calculator Suite",
  "sk": "Calculator Suite",
  "sl": "Paket za ra?unalo",
  "sv": "Calculator Suite",
  "tr": "Hesap Makinesi Süit",
  "uk": "??????????? ?????",
  "vi": "Calculator Suite",
  "zh": "Calculator Suite",
  "zh_CN": "?????",
  "zh_TW": "?????"};
